version: '3.8'
services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - business-service
      - food-service
      - cart-service
      - order-service
      - pay-service
    environment:
      - TZ=Asia/Shanghai

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:80"
    environment:
      - TZ=Asia/Shanghai

  business-service:
    build: ./business-service
    container_name: business-service
    ports:
      - "8082:80"
    environment:
      - TZ=Asia/Shanghai

  food-service:
    build: ./food-service
    container_name: food-service
    ports:
      - "8083:80"
    environment:
      - TZ=Asia/Shanghai

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "8084:80"
    environment:
      - TZ=Asia/Shanghai

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8085:80"
    environment:
      - TZ=Asia/Shanghai

  pay-service:
    build: ./pay-service
    container_name: pay-service
    ports:
      - "8086:80"
    environment:
      - TZ=Asia/Shanghai

  api:
    build: ./api
    container_name: api
    ports:
      - "8087:80"
    environment:
      - TZ=Asia/Shanghai

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: diancan
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./SQL.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 